const CatData = [
    {
        id:'1',
        link:"#",
        imgName:'cat1.png'
    },
    {
        id:'2',
        link:"#",
        imgName:'cat2.png'
    },
    {
        id:'3',
        link:"#",
        imgName:'cat3.png'
    },
    {
        id:'4',
        link:"#",
        imgName:'cat4.png'
    },
    {
        id:'5',
        link:"#",
        imgName:'cat5.png'
    },
    {
        id:'6',
        link:"#",
        imgName:'cat6.png'
    },
    {
        id:'7',
        link:"#",
        imgName:'cat7.png'
    },
    {
        id:'8',
        link:"#",
        imgName:'cat8.png'
    },
    {
        id:'9',
        link:"#",
        imgName:'cat9.png'
    },
    {
        id:'10',
        link:"#",
        imgName:'cat10.png'
    },
    {
        id:'11',
        link:"#",
        imgName:'cat11.png'
    },
]
export default CatData;